substitutions:
  name: boneio-dr-8ch-03-4023d4
  friendly_name: BoneIO Dimmer LED 4023d4
  serial_prefix: dim #Don't change it.

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: boneio.dimmer-led
    version: "0.3"

esp32:
  board: esp32dev

external_components:
  - source: github://boneIO-eu/esphome-LM75@main #Original source and thank you note for BTomala https://github.com/boneIO-eu/esphome-lm75
    components: [lm75]

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.1.0
    files:
      [
        devices/serial_no.yaml,
        devices/dimmer_i2c.yaml,
        devices/dimmer_ina219.yaml,
      ]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-dimmer_8ch-v0_3.yaml@latest
  import_full_config: true

pcf8574:
  - id: pcf_inputs
    address: 0x38

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome

http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false

web_server:
  port: 80
  local: true

text_sensor:
  - platform: version
    name: boneio-dimmer- Version
    icon: mdi:cube-outline
    entity_category: diagnostic
  - platform: ethernet_info
    ip_address:
      entity_category: diagnostic
      name: boneio-dimmer IP
  - platform: template
    name: Hostname
    id: hostname
    entity_category: diagnostic
    lambda: |-
      return id(eth).get_use_address();
    update_interval: 5min

globals:
  - id: lastDirection
    type: bool
    restore_value: no
    initial_value: "true"

binary_sensor:
  - platform: gpio
    id: btn_01
    name: IN_01
    pin:
      pcf8574: pcf_inputs
      number: 1
      mode:
        input: true
      inverted: true
    on_click:
      then:
        - if:
            condition:
              light.is_off: chl01_02
            then:
              - light.turn_on:
                  id: chl01_02
                  brightness: 1.0
              - lambda: "id(lastDirection) = false;"
            else:
              - light.turn_off: chl01_02
              - lambda: "id(lastDirection) = true;"
    on_press:
      then:
        - if:
            condition:
              or:
                - light.is_off: chl01_02
                - lambda: "return id(lastDirection) == true;"
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: btn_01
                  then:
                    - lambda: "id(lastDirection) = false;"
                    - light.dim_relative:
                        id: chl01_02
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: btn_01
                      - light.is_on: chl01_02
                      - lambda: "return id(chl01_02).current_values.get_brightness() > 0.2;"
                  then:
                    - lambda: "id(lastDirection) = true;"
                    - logger.log:
                        format: "Current brightness %.1f"
                        args: ["id(chl01_02).current_values.get_brightness()"]
                    - light.dim_relative:
                        id: chl01_02
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s

  - platform: gpio
    id: btn_02
    name: IN_02
    pin:
      pcf8574: pcf_inputs
      number: 2
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: IN_03
    pin:
      pcf8574: pcf_inputs
      number: 3
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: IN_04
    pin:
      pcf8574: pcf_inputs
      number: 4
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: IN_05
    pin:
      number: 36
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: IN_06
    pin:
      number: 39
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: IN_07
    pin:
      number: 34
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: IN_08
    pin:
      number: 35
      mode:
        input: true
      inverted: true

output:
  - platform: ledc
    pin: 33
    frequency: 1000Hz
    inverted: false
    id: chl01
  - platform: ledc
    pin: 32
    frequency: 1000Hz
    inverted: false
    id: chl02
  - platform: ledc
    pin: 12
    frequency: 1000Hz
    inverted: false
    id: chl03
  - platform: ledc
    pin: 14
    frequency: 1000Hz
    inverted: false
    id: chl04

  - platform: ledc
    pin: 13
    frequency: 1000Hz
    inverted: false
    id: chr01
  - platform: ledc
    pin: 15
    frequency: 1000Hz
    inverted: false
    id: chr02
  - platform: ledc
    pin: 2
    frequency: 1000Hz
    inverted: false
    id: chr03
  - platform: ledc
    pin: 17
    frequency: 1000Hz
    inverted: false
    id: chr04

light:
  - platform: cwww
    id: chl01_02
    name: "CHL_01_02"
    cold_white: chl01
    warm_white: chl02
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2000 K

  - platform: cwww
    id: chl03_04
    name: "CHL_03_04"
    cold_white: chl03
    warm_white: chl04
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2000 K

  - platform: cwww
    id: chr01_02
    name: "CHR_01_02"
    cold_white: chr01
    warm_white: chr02
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2000 K

  - platform: cwww
    id: chr03_04
    name: "CHR_03_04"
    cold_white: chr03
    warm_white: chr04
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2000 K

sensor:
  - platform: lm75
    id: boneIO_temp
    name: Temperature
    update_interval: 30s
    entity_category: diagnostic
    on_value_range:
      - above: 70.0
        then:
          - switch.turn_on: buzzer
      - below: 70.0
        then:
          - switch.turn_off: buzzer

switch:
  - platform: gpio
    id: buzzer
    name: Buzzer
    pin:
      pcf8574: pcf_inputs
      number: 0
      mode:
        output: true
      inverted: true
